# Generated by Django 3.1.7 on 2021-03-07 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_remove_post_tags_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags_id',
            field=models.ManyToManyField(default=None, to='posts.Tag'),
        ),
    ]
