# Generated by Django 3.1.7 on 2021-03-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='tags_id',
            field=models.ManyToManyField(blank=True, to='posts.Tag'),
        ),
    ]
