# Generated by Django 3.1.7 on 2021-03-14 11:49

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commentlike',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='commentlike',
            name='user_id',
        ),
        migrations.AddField(
            model_name='comment',
            name='dislikes',
            field=models.ManyToManyField(blank=True, related_name='Comment_dislike', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='Comment_like', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CommentDislike',
        ),
        migrations.DeleteModel(
            name='CommentLike',
        ),
    ]
