# Generated by Django 3.1.7 on 2021-03-17 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('posts', '0003_auto_20210312_1524'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('img', models.ImageField(blank=True, upload_to='avatars/')),
                ('status', models.CharField(blank=True, max_length=100)),
                ('dislikes', models.ManyToManyField(blank=True, related_name='dislikes_from_users', to=settings.AUTH_USER_MODEL)),
                ('favourite_posts', models.ManyToManyField(blank=True, related_name='favourite_posts', to='posts.Post')),
                ('likes', models.ManyToManyField(blank=True, related_name='likes_from_users', to=settings.AUTH_USER_MODEL)),
                ('subscribe_tags', models.ManyToManyField(blank=True, related_name='subscribe_tags', to='posts.Tag')),
                ('subscribe_users', models.ManyToManyField(blank=True, related_name='subscribe_users', to=settings.AUTH_USER_MODEL)),
                ('user_posts', models.ManyToManyField(blank=True, related_name='user_posts', to='posts.Post')),
            ],
        ),
    ]
